/**
 * @file    GoTransaction.h
 * @brief   Declares the GoPxLSdk.GoTransaction class.
 *
 * @internal
 * Copyright (C) 2022-2025 by LMI Technologies Inc.
 * Licensed under the MIT License.
 * Redistributed files must retain the above copyright notice.
 */
#ifndef GO_PXL_SDK_TRANSACTION_H
#define GO_PXL_SDK_TRANSACTION_H

#include <GoPxLSdk/GoRequest.h>
#include <GoPxLSdk/GoResponse.h>

class GoTransactionTests;

namespace GoPxLSdk
{
constexpr k64u DEFAULT_TRANSACTION_TIMEOUT_MSEC = 3 * 1000;  // 3,000 milliseconds = 3 seconds.

class GoRestClient;

class GoPxLSdkClass GoTransaction
{
public:
    /**
     * Constructs GoTransaction.
     *
     * @public                                    @memberof GoTransaction
     * @version                                   Introduced in 0.2.1.53.
     */
    GoTransaction() = default;

    /**
     * Transaction handle to simplify working with asynchronous result data.
     *
     * @public                                    @memberof GoTransaction
     * @version                                   Introduced in 0.2.1.53.
     * @param request                             Request to handle.
     * @throws GoPxLSdk::GoChannelError           If the request times out.
     * @throws GoPxLSdk::GoRequestError           If the server responds with a fail status for the request.
     */
    GoTransaction(const GoRequest& request);

    /**
     * Checks the future transaction response value without returning it. Waits until the response is available.
     *
     * @public                                    @memberof GoTransaction
     * @version                                   Introduced in 0.2.1.53.
     * @param timeoutInMilliseconds               Time to wait for the response in milliseconds. Default value is `DEFAULT_TRANSACTION_TIMEOUT_MSEC`.
     * @throws GoPxLSdk::GoRequestError           If the server responds with a failed status for the request.
     * @throws GoPxLSdk::GoChannelError           If the request times out.
     */
    void CheckResponse(k64u timeoutInMilliseconds = DEFAULT_TRANSACTION_TIMEOUT_MSEC);

    /**
     * Gets the future transaction response value. Waits until the response is available.
     *
     * @public                                    @memberof GoTransaction
     * @version                                   sIntroduced in 0.2.1.53.
     * @param timeoutInMilliseconds               Time to wait for the response in milliseconds. Default value is `DEFAULT_TRANSACTION_TIMEOUT_MSEC`.
     * @return                                    The request's response.
     * @throws GoPxLSdk::GoRequestError           If the server responds with a failed status for the request.
     * @throws GoPxLSdk::GoChannelError           If the request times out.
     */
    const GoRequestResponse& GetResponse(k64u timeoutInMilliseconds = DEFAULT_TRANSACTION_TIMEOUT_MSEC);

    /**
     * Gets the transaction request value. Since a transaction is initiated with a request, this method
     * should always succeed.
     *
     * @public                                    @memberof GoTransaction
     * @version                                   Introduced in 0.2.1.53.
     */
    const GoRequest& GetRequest();

    /**
     * Gets the future which stores the transaction response value.
     *
     * @public                          @memberof GoTransaction
     * @version                         Introduced in 0.2.1.53
     * @return                          The Future which holds the response.
     */
    std::shared_future<GoRequestResponse>& GetResponseFuture();

protected:
    /**
     * Sets the future which stores the transaction response value.
     *
     * @public                          @memberof GoTransaction
     * @param response                  GoRequestResponse object
     * @version                         Introduced in 0.2.1.53
     */
    void OnResponse(const std::shared_ptr<GoRequestResponse>& response);

    /**
     * Sets the future error and forces GetResponse() to throw exception e wrapped in GoChannelError.
     *
     * @public                          @memberof GoTransaction
     * @param e                         Exception generated by GoCtrlChannel read or write thread.
     * @version                         Introduced in 0.2.1.53
     */
    void OnError(const std::exception& e);

private:
    GoRequest request;
    std::shared_ptr<std::promise<GoRequestResponse>> promise;
    std::shared_future<GoRequestResponse> futureResponse;

    friend class GoRestClient;
    friend class ::GoTransactionTests;
};

}

#endif
